config/routes.rb
Rails.application.routes.draw do
  get 'locations/index'
  get 'locations/posts'
  get 'helpful/index'
  resources :locations
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "home#index"
  
  resources :users, :only => [:posts, :index, :show]
  
  resources :locations, :only => [:new] do
    resources :reviews, only: [:index, :create]
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/location.rb
class Location < ApplicationRecord
  mount_uploader :location_image, ImageUploader

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :reviews, dependent: :destroy

  has_many :favorites, dependent: :destroy

  belongs_to :user, optional: true

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end
  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
    @q = Location.ransack(params[:q])
    @locations = @q.result(distinct: true)
  end
  
  def new
    @location = Location.new
  end
  
  def create
    @location = Location.new(location_params)
    @location.user_id = current_user.id
    @location.save
    redirect_to locations_posts_path
  end
  
  def posts
    @locations = current_user.locations.all
  end
  
  def show
    @location = Location.find(params[:id])
    @review = Review.new
  end
  
  def destroy
    @location = Location.find(params[:id])
    if @location.user != current_user
      redirect_to locations_posts_path
    else
      @location.destroy
      redirect_to locations_posts_path
    end
  end
  
  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update(params.require(:location).permit(:location_name,:introduction,:address,:price,:location_image))
      redirect_to locations_posts_path
    else
      render "edit"
    end
  end
  
  private
    def location_params
      params.require(:location).permit(:location_name,:introduction,:address,:price,:location_image)
    end
end

app/views/locations/edit.html.erb
<div class="edit-main">
  <div class="cont_title1">
    <h1>スポット編集</h1><hr>
  </div>
  <%= form_with model: @location, local: true  do |f| %>
    <table class="location_info_base4">
      <thead>
        <tr class="arrow_box">
          <th><%= f.label :location_name,'スポット名' %></th>
          <td><%= f.text_field :location_name, placeholder: 'スポット名を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :introduction,'スポット紹介' %></th>
          <td><%= f.text_area :introduction, placeholder: '例）越谷レイクタウンは埼玉県越谷市にある大型ショッピングモールです！中には映画館などもあるのでおすすめです！' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :location_image,'画像を選択' %></th>
          <td><%= f.file_field :location_image %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :address,'住所を入力' %></th>
          <td><%= f.text_field :address, placeholder: '住所を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :price,'予算を入力' %></th>
          <td><%= f.number_field :price, placeholder: '予算を入力' %></td>
        </tr>
      </thead>
    </table>
    <div class="done_button">
      <ul>
        <li><%= f.submit "スポット編集を完了する" %></li>
        <li><%= link_to "登録済みスポット一覧に戻る", locations_posts_path %></li>
      </ul>
    </div>
  <% end %>
</div>

app/views/locations/index.html.erb
<div class="index-main">
  <div class="cont_title2">
    <h1>みんなのスポット一覧</h1><hr>
  </div>
  <table class="location_info_base2">
    <thead>
      <% @locations.each do |location| %>
        <tr class="arrow_box">
          <th>スポット名</th>
          <td><%= location.location_name %></td>
        </tr>
        <tr class="arrow_box">
          <th>料金・予算</th>
          <td><%= location.price %>円</td>
        </tr>
        <tr class="arrow_box">
          <th>スポット画像</th>
          <% if location.location_image? %>
            <td><img src=<%= location.location_image.to_s %> class = "icon_imagea"></td>
          <% else %>
            <td><%= image_tag src='default.jpeg', class: "icon_imagea", alt: "ユーザーアイコン" %></td>
          <% end %>
        </tr>
        <tr class="arrow_box">
          <th>どんな所？</th>
          <td><%= location.introduction %></td>
        </tr>
        <tr class="arrow_box">
          <th>住所</th>
          <td><%= location.address %></td>
        </tr>
        <tr class="arrow_box">
          <th>詳細</th>
          <td><%= link_to "詳細を見る・レビューを書く", location %></td>
        </tr>
        <tr class="arrow_box">
          <th>いいね</th>
          <td>
            <% if current_user.already_favorited?(location) %>
              <%= link_to location_favorites_path(location), method: :delete do %>
                <i class="fas fa-heart"></i>
              <% end %>
              <%= location.favorites.count %>
            <% else %>
              <%= link_to location_favorites_path(location), method: :post do %>
                <i class="far fa-heart"></i>
              <% end %>
              <%= location.favorites.count %>
            <% end %>
          </td>
        </tr>
        <tr class="touroku">
          <% if location.user == current_user %>
            <th>消去</th>
            <td><%= link_to "消去しますか？", location, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
          <% else %>
          <% end %>
        </tr>
      <% end %>
    </thead>
  </table>
</div>

app/views/locations/new.html.erb
<div class="new-main">
  <div class="cont_title5">
    <h1>スポット情報登録</h1><hr>
  </div>
  <%= form_with model: @location, local: true  do |f| %>
    <table class="location_info_base5">
      <thead>
        <tr class="arrow_box">
          <th><%= f.label :location_name,'スポット名' %></th>
          <td><%= f.text_field :location_name, placeholder: 'スポット名を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :introduction,'スポット紹介' %></th>
          <td><%= f.text_area :introduction, placeholder: 'スポット紹介を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :location_image,'画像を選択' %></th>
          <td><%= f.file_field :location_image %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :address,'住所を入力' %></th>
          <td><%= f.text_field :address, placeholder: '住所を入力' %></td>
        </tr>
        <tr class="arrow_box">
          <th><%= f.label :price,'料金・予算を入力' %></th>
          <td><%= f.number_field :price, placeholder: '予算を入力' %></td>
        </tr>
      </thead>
    </table>
    <div class="done_button">
      <%= f.submit '登録完了する' %>
    </div>
  <% end %>
</div>

app/views/locations/posts.html.erb
<div class="post-main">
  <div class="cont_title">
    <h1>登録済みスポット一覧（自分で登録）</h1><hr>
  </div>
  <table class="location_info_base1">
    <thead>
      <% @locations.each do |location| %>
        <tr class="arrow_box">
          <th>スポット名</th>
          <td><%= location.location_name %></td>
        </tr>
        <tr class="arrow_box">
          <th>料金・予算</th>
          <td><%= location.price %>円</td>
        </tr>
        <tr class="arrow_box">
          <th>スポット画像</th>
          <% if location.location_image? %>
            <td><img src=<%= location.location_image.to_s %> class = "icon_imagea"></td>
          <% else %>
            <td><%= image_tag src='default.jpeg', class: "icon_imagea", alt: "デフォルト画像" %></td>
          <% end %>
        </tr>
        <tr class="arrow_box">
          <th>どんな所？</th>
          <td><%= location.introduction %></td>
        </tr>
        <tr class="arrow_box">
          <th>住所</th>
          <td><%= location.address %></td>
        </tr>
        <tr class="touroku">
          <th>詳細・編集・削除</th>
          <td><%= link_to "詳細を見る", location %><br><%= link_to "編集", edit_location_path(location) %><br><%= link_to "削除しますか？", location, method: :delete, data: { confirm: "本当に削除しますか？" } %> <br>
        </tr>
      <% end %>
    </thead>
  </table>
</div>
 

app/views/locations/show.html.erb
<div class="show-main">
  <div class="cont_title3">
    <h1>スポット詳細ページ</h1><hr>
  </div>
  <table class="location_info_base3">
    <thead>
      <tr class="arrow_box">
        <th>スポット名</th>
        <td><%= @location.location_name %></td>
      </tr>
      <tr class="arrow_box">
        <th>料金・予算</th>
        <td><%= @location.price %>円</td>
      </tr>
      <tr class="arrow_box">
        <th>スポット画像</th>
        <% if @location.location_image? %>
          <td><img src=<%= @location.location_image.to_s %> class = "icon_imagea"></td>
        <% else %>
          <td><%= image_tag src='default.jpeg', class: "icon_imagea", alt: "ユーザーアイコン" %></td>
        <% end %>
      </tr>
      <tr class="arrow_box">
        <th>住所</th>
        <td><%= @location.address %><div id="map"></div></td>
      </tr>
      <tr class="arrow_box">
        <th>スポット紹介</th>
        <td><%= @location.introduction %></td>
      </tr>
      <tr class="arrow_box">
        <th>口コミを見る</th>
        <td><%= link_to "レビューを見る", location_reviews_path(@location), class: "button light ml-3 mt-3" %></td>
      </tr>
      <tr class="arrow_box">
          <th>いいね</th>
          <td>
            <% if current_user.already_favorited?(@location) %>
              <%= link_to location_favorites_path(@location), method: :delete do %>
                <i class="fas fa-heart"></i>
              <% end %>
              <%= @location.favorites.count %>
            <% else %>
              <%= link_to location_favorites_path(@location), method: :post do %>
                <i class="far fa-heart"></i>
              <% end %>
              <%= @location.favorites.count %>
            <% end %>
          </td>
        </tr>
    </thead>
  </table>
  <%= render 'reviews/form', review: @review, location: @location %>
</div>