config/routes.rb
Rails.application.routes.draw do
  get 'locations/index'
  get 'locations/posts'
  get 'helpful/index'
  resources :locations
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "home#index"
  
  resources :users, :only => [:posts, :index, :show]
  
  resources :locations, :only => [:new] do
    resources :reviews, only: [:index, :create]
    resource :favorites, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/a2ed1e393c.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
    <% if user_signed_in? %>
    <header class="page-header" id="header">
      <div class="navbar-item">
        <%= search_form_for @q  do |f| %>
          <%= f.search_field :address_cont, placeholder: '例）埼玉県春日部市' %>
          <%= f.submit "検索", class: "button2"%>
        <% end %>
        <a href="/" class="title is-4" style="font-family: cursive;">Asobuno Tanosiiina</a>
        <ul class="menu">
          <li>
            <div class="button-color1 logout">現在ログイン中：<%= current_user.username %></div>
            <ul>
			        <li><%= link_to "ユーザー編集ページ", edit_user_registration_path, class: "header-pl" %></li>
			        <li><%= link_to "ユーザー登録一覧", users_path, class: "header-pl" %></li>
		        </ul>
	        </li>
	     </ul>
      </div>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end1">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "TOP", root_path, class: "headbottan button-color" %>
              </p>
              <p class="control">
                <%= link_to "Asobuno Tanosiiinaとは?", helpful_index_path, class: "headbottan button-color" %>
              </p>
              <p class="control">
                <%= link_to "スポット登録", new_location_path, class: "headbottan button-color" %>
              </p>
              <p class="control">
                <%= link_to "スポット登録一覧", locations_posts_path, class: "headbottan button-color" %>
              </p>
              <p class="control">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "headbottan button-color" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="navbar-item">
        <a href="/" class="title is-4" style="font-family: cursive;">Asobuno Tanosiiina</a>
      </div>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end2">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "TOP", root_path, class: "headbottan1 button-color" %>
              </p>
              <p class="control">
                <%= link_to "Asobuno Tanosiiinaとは?", helpful_index_path, class: "headbottan1 button-color" %>
              </p>
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "headbottan1 button-color" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "headbottan1 button-color" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <footer id="footer01" class="footer outer-block">
      <div class="logo">
        <a href="/" class="title is-5" style="font-family: cursive;">Asobuno Tanosiiina</a>
      </div>
      <p class="copyright">
        © 2021 Copyright: Asobuno Tanosiiina
      </p>
    </footer>
  </body>
</html>